import { ModelBundle } from './schema';
/** GENERATED BY scripts/train-model.ts - DO NOT EDIT BY HAND. Run `npm run train` to rebuild.
 * Trained on seeded synthetic episodes, so the metrics below are held-out synthetic metrics.
 * They are not evidence of real-world disaster detection skill.
 */
export const model: ModelBundle = {
 "version": "sentinel-ml-1.0",
 "algorithm": "Standardised softmax regression (state) + logistic regression (30 s early warning), Adam, L2 2e-4",
 "trainedAt": "2026-09-12T04:37:00.370Z",
 "window": 20,
 "tickSeconds": 1.5,
 "dataset": {
  "episodes": 1170,
  "samples": 106747,
  "generator": "scripts/train-model.ts - seeded synthetic episodes with noise, calibration offsets, dropout and nuisance events",
  "seed": 20260911
 },
 "models": {
  "node-1": {
   "classes": [
    {
     "id": "baseline",
     "label": "Baseline",
     "hazard": false,
     "description": "Ambient vibration only. No onset pattern in the window."
    },
    {
     "id": "seismic",
     "label": "Seismic event",
     "hazard": true,
     "description": "Sustained acceleration envelope corroborated by the shock and acoustic comparators."
    },
    {
     "id": "machinery",
     "label": "Machinery or traffic",
     "hazard": false,
     "description": "Repeated shock and acoustic trips with low peak acceleration: the signature of nearby vehicles or plant, not ground motion."
    },
    {
     "id": "disturbance",
     "label": "Node disturbance",
     "hazard": false,
     "description": "Isolated acceleration spikes with no envelope. The node itself was knocked or handled."
    }
   ],
   "features": [
    "accel_now",
    "accel_mean",
    "accel_max",
    "accel_std",
    "accel_slope",
    "accel_share_high",
    "shock_duty",
    "shock_edges",
    "sound_duty",
    "sound_edges",
    "co_active",
    "votes_now"
   ],
   "mean": [
    0.072084,
    0.071438,
    0.170534,
    0.038856,
    0.000058,
    0.096815,
    0.116719,
    0.031958,
    0.073295,
    0.027916,
    0.100082,
    0.274491
   ],
   "scale": [
    0.161715,
    0.13776,
    0.29585,
    0.073397,
    0.006264,
    0.266608,
    0.244023,
    0.057758,
    0.176622,
    0.056424,
    0.246259,
    0.738455
   ],
   "weights": [
    [
     -3.051339,
     -2.884463,
     -2.747191,
     -2.174545,
     2.072609,
     -0.116407,
     -1.5082,
     -0.123653,
     -1.739671,
     0.141798,
     -0.750995,
     -0.702986
    ],
    [
     1.9965,
     4.124784,
     0.084891,
     -0.726819,
     -1.290179,
     1.114641,
     0.615614,
     -0.562554,
     -0.214138,
     -0.338403,
     0.698769,
     0.364954
    ],
    [
     -1.26029,
     -2.70403,
     -1.407713,
     -1.196084,
     0.231205,
     -1.940906,
     4.047697,
     0.356395,
     3.253622,
     0.195004,
     0.228951,
     0.551705
    ],
    [
     0.755408,
     -4.575153,
     2.169182,
     1.988466,
     -0.531316,
     -0.311525,
     -1.611514,
     0.29964,
     -1.355363,
     -0.101801,
     -0.773581,
     -0.272143
    ]
   ],
   "bias": [
    -2.574316,
    2.140058,
    1.39852,
    -1.023925
   ],
   "escalation": {
    "weights": [
     0.56011,
     -1.026,
     -0.060256,
     0.030302,
     0.195718,
     0.536298,
     -1.293346,
     0.293822,
     0.786854,
     -0.096032,
     0.899152,
     1.285793
    ],
    "bias": 0.481455,
    "horizonSeconds": 30,
    "alertThreshold": 0.46
   },
   "metrics": {
    "trainSamples": 28460,
    "testSamples": 18970,
    "accuracy": 0.965683,
    "macroF1": 0.947127,
    "perClass": [
     {
      "id": "baseline",
      "precision": 0.978096,
      "recall": 0.976462,
      "f1": 0.977278,
      "support": 13170
     },
     {
      "id": "seismic",
      "precision": 0.975443,
      "recall": 0.974658,
      "f1": 0.97505,
      "support": 2486
     },
     {
      "id": "machinery",
      "precision": 0.882782,
      "recall": 0.925709,
      "f1": 0.903736,
      "support": 2221
     },
     {
      "id": "disturbance",
      "precision": 0.971259,
      "recall": 0.896615,
      "f1": 0.932445,
      "support": 1093
     }
    ],
    "escalation": {
     "precision": 0.257318,
     "recall": 0.594345,
     "f1": 0.359146,
     "auc": 0.657176,
     "medianLeadSeconds": 48,
     "positives": 3254
    }
   }
  },
  "node-2": {
   "classes": [
    {
     "id": "baseline",
     "label": "Baseline",
     "hazard": false,
     "description": "Soil moisture and rain pad are within their settled range."
    },
    {
     "id": "flood",
     "label": "Flooding",
     "hazard": true,
     "description": "Rising rain wetness and soil saturation with the float switch carrying water level."
    },
    {
     "id": "irrigation",
     "label": "Local wetting",
     "hazard": false,
     "description": "Soil moisture rising on its own while the rain pad stays dry: irrigation, a leak, or a hose."
    },
    {
     "id": "shower",
     "label": "Passing shower",
     "hazard": false,
     "description": "A short rain spike that decays without meaningfully saturating the soil."
    },
    {
     "id": "float_fault",
     "label": "Float switch fault",
     "hazard": false,
     "description": "Float switch reads high while rain and soil stay dry: a jammed or debris-held float."
    }
   ],
   "features": [
    "moist_now",
    "moist_mean",
    "moist_max",
    "moist_std",
    "moist_slope",
    "moist_share_high",
    "rain_now",
    "rain_mean",
    "rain_max",
    "rain_slope",
    "rain_share_high",
    "float_duty",
    "float_edges",
    "wet_co"
   ],
   "mean": [
    50.882436,
    49.66159,
    52.948013,
    1.822013,
    0.086155,
    0.236816,
    18.842502,
    17.976763,
    23.720446,
    0.062267,
    0.151015,
    0.296835,
    0.012987,
    0.09648
   ],
   "scale": [
    19.043125,
    18.274802,
    18.905395,
    1.753249,
    0.237319,
    0.414063,
    23.347597,
    22.055831,
    23.922052,
    0.420019,
    0.338087,
    0.440153,
    0.030653,
    0.283968
   ],
   "weights": [
    [
     -1.654324,
     -0.534823,
     -1.258159,
     -2.685864,
     -1.438161,
     -0.025252,
     -1.859365,
     -0.76198,
     -2.535599,
     0.827606,
     0.070335,
     -2.495049,
     -0.164814,
     0.192625
    ],
    [
     0.661355,
     -0.132395,
     0.094715,
     1.540777,
     1.435962,
     -0.257858,
     1.652858,
     0.664811,
     0.508323,
     0.158845,
     0.33992,
     -0.189335,
     -0.058902,
     0.787337
    ],
    [
     1.051978,
     0.248901,
     0.740194,
     2.728097,
     1.219256,
     1.471312,
     -1.46942,
     -1.188125,
     -1.463833,
     -1.00724,
     -0.463757,
     -1.123409,
     -0.198336,
     -0.375468
    ],
    [
     -0.195605,
     1.066506,
     0.628885,
     -2.653214,
     -1.385856,
     -2.039822,
     -0.019449,
     1.427079,
     3.836382,
     -0.318803,
     -0.153365,
     -2.584455,
     -0.133302,
     -1.707028
    ],
    [
     -0.647311,
     -0.593274,
     -0.60827,
     -0.478699,
     -0.561245,
     -0.324705,
     -0.502508,
     -0.49655,
     -0.579187,
     0.21343,
     -0.255581,
     3.11802,
     0.434055,
     -0.149388
    ]
   ],
   "bias": [
    -3.512241,
    2.451241,
    -0.475652,
    0.724768,
    -2.116107
   ],
   "escalation": {
    "weights": [
     2.170226,
     -1.491466,
     -0.243456,
     -0.336275,
     0.531989,
     -2.214931,
     4.07533,
     0.574631,
     -2.085043,
     0.465422,
     -2.047859,
     -0.711809,
     0.230127,
     3.920617
    ],
    "bias": -1.214029,
    "horizonSeconds": 30,
    "alertThreshold": 0.8
   },
   "metrics": {
    "trainSamples": 35528,
    "testSamples": 23789,
    "accuracy": 0.9583,
    "macroF1": 0.954658,
    "perClass": [
     {
      "id": "baseline",
      "precision": 0.913278,
      "recall": 0.965272,
      "f1": 0.938555,
      "support": 7026
     },
     {
      "id": "flood",
      "precision": 0.991267,
      "recall": 0.957811,
      "f1": 0.974252,
      "support": 4148
     },
     {
      "id": "irrigation",
      "precision": 0.991882,
      "recall": 0.972296,
      "f1": 0.981991,
      "support": 3393
     },
     {
      "id": "shower",
      "precision": 0.90703,
      "recall": 0.85216,
      "f1": 0.87874,
      "support": 3240
     },
     {
      "id": "float_fault",
      "precision": 0.999499,
      "recall": 1,
      "f1": 0.999749,
      "support": 5982
     }
    ],
    "escalation": {
     "precision": 0.693046,
     "recall": 0.81028,
     "f1": 0.747092,
     "auc": 0.971209,
     "medianLeadSeconds": 24,
     "positives": 1070
    }
   }
  }
 }
};
