import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = process.env.TEST_URL || 'http://localhost:3000';
try {
 await page.goto(base, { waitUntil: 'domcontentloaded' });
 await page.getByRole('heading', { name:'Welcome to Sentinel.' }).waitFor();
 await page.waitForTimeout(700);
 await page.screenshot({path:'artifacts/login.png',fullPage:true});
 await page.getByLabel('Email address').fill('wrong@example.com');
 await page.getByLabel('Password', { exact:true }).fill('wrong');
 await page.getByRole('button',{name:'Sign in to dashboard'}).click();
 await page.getByRole('alert').filter({hasText:'Credentials do not match'}).waitFor();
 await page.getByRole('button',{name:'Enter simulation demo'}).click();
 await page.getByRole('heading',{name:'Network overview'}).waitFor();
 await page.getByText('All systems normal',{exact:true}).waitFor();
 await page.waitForTimeout(4500);
 await page.screenshot({path:'artifacts/dashboard.png',fullPage:true});
 const initial = await page.request.get(`${base}/api/events`);
 assert.equal(initial.status(),200);
 assert.ok((await initial.json()).length >= 3,'events persisted');
 await page.getByRole('button',{name:'View node details'}).first().click();
 await page.getByRole('dialog',{name:'Node 01 live details'}).waitFor();
 await page.getByRole('heading',{name:'Why this tier?'}).waitFor();
 await page.getByRole('button',{name:'Close node details'}).click();
 await page.getByRole('button',{name:'Network map',exact:true}).click();
 await page.locator('.large-map .map-node').first().waitFor();
 await page.locator('.large-map .map-node').first().click();
 await page.getByRole('dialog',{name:'Node 01 live details'}).waitFor();
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.getByRole('button',{name:'Run simulation',exact:true}).click();
 await page.getByRole('button',{name:'Start scenario',exact:true}).click();
 await page.getByText('Approaching earthquake',{exact:true}).waitFor();
 await page.waitForTimeout(46000);
 const events = await (await page.request.get(`${base}/api/events`)).json();
 assert.ok(events.some(e => e.nodeId === 'node-1' && e.tier === 'Watch'),'scenario reaches Watch');
 assert.ok(events.some(e => e.nodeId === 'node-1' && e.tier === 'Warning'),'scenario reaches Warning');
 assert.ok(events.some(e => e.nodeId === 'node-1' && e.tier === 'Critical'),'scenario reaches Critical');
 await page.screenshot({path:'artifacts/critical.png',fullPage:true});
 await page.getByRole('button',{name:'Reset',exact:true}).click();
 await page.getByText('All systems normal',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Alerts & history',exact:true}).click();
 await page.getByLabel('Filter events by tier').selectOption('Critical');
 assert.ok(await page.locator('tbody tr').count() > 0);
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByRole('button',{name:'USB / LoRa gateway'}).click();
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.getByText('Awaiting data',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Hardware mode',exact:true}).click();
 await page.getByRole('button',{name:'Simulation Server-generated sensor telemetry'}).click();
 await page.getByText('All systems normal',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true,'no mobile page overflow');
 assert.deepEqual(errors,[],'no browser runtime errors');
 console.log('PASS: Login, live telemetry, persistence, node drawer, map marker, scenario Watch→Warning→Critical, history filters, hardware offline, reset, and mobile layout.');
} finally { await browser.close(); }
