'use client';
import { useState } from 'react';
import { Download, ListFilter, ArrowUpRight, CheckCheck } from 'lucide-react';
import { HazardEvent, Tier } from '@/lib/types';
import { Badge } from './node-card';
export function timeLabel(timestamp: string) { return new Date(timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }); }
export default function EventTable({ events, compact = false, onSelect }: { events: HazardEvent[]; compact?: boolean; onSelect: (id: string) => void }) {
 const [node, setNode] = useState('all'); const [tier, setTier] = useState('all'); const filtered = events.filter(e => (node === 'all' || e.nodeId === node) && (tier === 'all' || e.tier === tier));
 function download() { const columns = ['Timestamp','Node','Hazard','Tier','Confidence','Signals','Latitude','Longitude']; const rows = filtered.map(e => [e.timestamp,e.nodeName,e.hazard,e.tier,e.score,e.contributors.join('; '),e.location.lat,e.location.lng]); const csv = [columns,...rows].map(r => r.map(v => `"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'); const a = document.createElement('a'); const url = URL.createObjectURL(new Blob([csv], { type:'text/csv' })); a.href = url; a.download = 'sentinel-mesh-events.csv'; a.click(); URL.revokeObjectURL(url); }
 if (compact) return <div className="compact-events">{events.slice(0,3).map(e => <button key={e.id} className="compact-event" onClick={() => onSelect(e.nodeId)}><span className={`event-dot tier-${e.tier.toLowerCase()}`}><CheckCheck size={15} /></span><span><strong>{e.tier === 'Normal' ? `${e.nodeName} · ${e.hazard} baseline` : `${e.hazard} ${e.tier.toLowerCase()} · ${e.nodeName}`}</strong><small>{e.contributors.length ? `${e.contributors.length} corroborating signals` : 'Readings within normal range'}</small></span><time>{timeLabel(e.timestamp).slice(0,5)}</time></button>)}{!events.length && <div className="empty-state">No events yet. Waiting for node telemetry.</div>}</div>;
 return <section className="neo event-table-panel"><div className="table-toolbar"><div><ListFilter size={16} /><select aria-label="Filter events by node" value={node} onChange={e => setNode(e.target.value)}><option value="all">All nodes</option><option value="node-1">Node 01</option><option value="node-2">Node 02</option></select><select aria-label="Filter events by tier" value={tier} onChange={e => setTier(e.target.value)}><option value="all">All risk tiers</option>{(['Normal','Watch','Warning','Critical'] as Tier[]).map(t => <option key={t}>{t}</option>)}</select><span className="muted">{filtered.length} events</span></div><button className="button secondary small" onClick={download}><Download size={15} /> Export CSV</button></div><div className="table-scroll"><table><thead><tr><th>Timestamp</th><th>Node / hazard</th><th>Risk tier</th><th>Confidence</th><th>Contributing evidence</th><th>GPS location</th><th /></tr></thead><tbody>{filtered.map(e => <tr key={e.id}><td><strong>{timeLabel(e.timestamp)}</strong><small>{new Date(e.timestamp).toLocaleDateString('en-IN')}</small></td><td><strong>{e.nodeName}</strong><small>{e.hazard}</small></td><td><Badge tier={e.tier} /></td><td>{e.score}%</td><td className="evidence-cell">{e.contributors.join(' + ') || 'Baseline · no corroborating signals'}</td><td className="coordinates">{e.location.lat.toFixed(4)}° N<br />{e.location.lng.toFixed(4)}° E</td><td><button className="icon-button" title="Open node details" onClick={() => onSelect(e.nodeId)}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><CheckCheck size={30} /><h3>No matching events</h3><p>Try a different filter or start a simulation.</p></div>}</div></section>;
}
